apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: skillfybank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: jayantrajput/skillfybank-account:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: skillfybank-config
            - secretRef:
                name: skillfybank-db-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
